/**
 * Web Push Subscription client utility
 * Handles permission requests, service worker registration binding,
 * and subscription registration with the campus notification service.
 */

function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");
  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

export interface PushStatus {
  supported: boolean;
  permission: NotificationPermission | "unsupported";
  isSubscribed: boolean;
  endpoint?: string | undefined;
}

/**
 * Inspect current push notification capability and active subscription status
 */
export async function getPushSubscriptionStatus(): Promise<PushStatus> {
  if (
    typeof window === "undefined" ||
    !("serviceWorker" in navigator) ||
    !("PushManager" in window) ||
    !("Notification" in window)
  ) {
    return {
      supported: false,
      permission: "unsupported",
      isSubscribed: false,
    };
  }

  const permission = Notification.permission;
  try {
    const reg = await navigator.serviceWorker.ready;
    const subscription = await reg.pushManager.getSubscription();
    return {
      supported: true,
      permission,
      isSubscribed: Boolean(subscription),
      endpoint: subscription?.endpoint,
    };
  } catch {
    return {
      supported: true,
      permission,
      isSubscribed: false,
    };
  }
}

/**
 * Request notification permissions and register push subscription
 */
export async function subscribeToPushNotifications(): Promise<{
  success: boolean;
  error?: string;
}> {
  if (
    typeof window === "undefined" ||
    !("serviceWorker" in navigator) ||
    !("PushManager" in window) ||
    !("Notification" in window)
  ) {
    return { success: false, error: "Web Push is not supported on this browser or platform." };
  }

  try {
    const permission = await Notification.requestPermission();
    if (permission !== "granted") {
      return {
        success: false,
        error:
          "Notification permission was not granted. Please allow notifications in browser settings.",
      };
    }

    // Fetch VAPID key
    const vapidRes = await fetch("/api/v1/notifications/push/vapid-key");
    if (!vapidRes.ok) {
      return { success: false, error: "Failed to fetch push server configuration." };
    }
    const { publicKey } = await vapidRes.json();

    const reg = await navigator.serviceWorker.ready;
    let subscription = await reg.pushManager.getSubscription();

    if (!subscription) {
      const appServerKey = urlBase64ToUint8Array(publicKey);
      subscription = await reg.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: appServerKey as unknown as BufferSource,
      });
    }

    const subJson = subscription.toJSON();
    if (!subJson.endpoint || !subJson.keys?.p256dh || !subJson.keys?.auth) {
      return { success: false, error: "Incomplete push subscription generated by browser." };
    }

    // Register subscription on backend
    const saveRes = await fetch("/api/v1/notifications/push/subscribe", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        endpoint: subJson.endpoint,
        keys: {
          p256dh: subJson.keys.p256dh,
          auth: subJson.keys.auth,
        },
      }),
    });

    if (!saveRes.ok) {
      const err = await saveRes.json().catch(() => ({}));
      return { success: false, error: err.detail || "Failed to register subscription on server." };
    }

    return { success: true };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : "Push subscription failed.";
    return { success: false, error: msg };
  }
}

/**
 * Unsubscribe current browser session from Web Push
 */
export async function unsubscribeFromPushNotifications(): Promise<boolean> {
  if (typeof window === "undefined" || !("serviceWorker" in navigator)) {
    return false;
  }
  try {
    const reg = await navigator.serviceWorker.ready;
    const subscription = await reg.pushManager.getSubscription();
    if (subscription) {
      return await subscription.unsubscribe();
    }
    return true;
  } catch {
    return false;
  }
}
