"use client";

import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { GlassCard } from "@/components/glass-card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { ShieldAlert, KeyRound, ArrowRight } from "lucide-react";
import { toast } from "sonner";

export default function MfaPage() {
  const router = useRouter();
  const [code, setCode] = React.useState("");
  const [isVerifying, setIsVerifying] = React.useState(false);

  const handleVerify = (e: React.FormEvent) => {
    e.preventDefault();
    if (code.length < 6) return;

    setIsVerifying(true);
    setTimeout(() => {
      setIsVerifying(false);
      toast.success("Two-factor authentication verified successfully!");
      router.push("/admin/dashboard");
    }, 600);
  };

  return (
    <div className="flex min-h-screen items-center justify-center p-4 bg-background text-foreground">
      <GlassCard className="w-full max-w-md p-8 text-center border-brand-500/30">
        <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-amber-500/10 text-amber-600 dark:text-amber-400">
          <ShieldAlert className="h-6 w-6" />
        </div>

        <h1 className="mt-4 font-heading text-2xl font-bold">Two-Factor Authentication</h1>
        <p className="mt-1 text-xs text-muted-foreground">
          Enter the 6-digit TOTP code generated by your Authenticator App (Google Authenticator,
          Duo, or 1Password)
        </p>

        <form onSubmit={handleVerify} className="mt-6 flex flex-col gap-4">
          <div className="relative">
            <KeyRound className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              type="text"
              maxLength={6}
              value={code}
              onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))}
              placeholder="000000"
              className="pl-10 text-center font-mono text-xl tracking-widest"
              autoFocus
            />
          </div>

          <Button
            type="submit"
            size="lg"
            disabled={code.length < 6 || isVerifying}
            className="w-full"
          >
            {isVerifying ? "Verifying TOTP..." : "Verify & Continue"}
            <ArrowRight className="ml-2 h-4 w-4" />
          </Button>
        </form>

        <div className="mt-6 flex flex-col gap-2 text-xs text-muted-foreground">
          <button
            type="button"
            onClick={() => {
              setCode("123456");
              toast.info("Autofilled demo TOTP code: 123456");
            }}
            className="text-brand-600 hover:underline dark:text-brand-400"
          >
            Autofill Demo Code (123456)
          </button>
          <Link href="/login" className="hover:underline">
            Cancel and return to login
          </Link>
        </div>
      </GlassCard>
    </div>
  );
}
